INSERT INTO 
products (id, name, category, description) 
VALUES
(1, 'Poire', 'fruits', 'Description de la poire.'),
(2, 'Clémentine', 'fruits', 'Description de la clémentine.'),
(3, 'Banane', 'fruits', 'Description de la banane.'),
(4, 'Pomme', 'fruits', 'Description de la pomme.'),
(5, 'Kiwi', 'fruits', 'Description du kiwi.'),
(6, 'Raisin', 'fruits', 'Description du raisin.'),
(7, 'Citron', 'fruits', 'Description du citron.'),
(8, 'Nectarine', 'fruits', 'Description de la nectarine.'),
(9, 'Groseille', 'fruits', 'Description de la groseille.'),
(10, 'Pomme', 'fruits', 'Description de la pomme.'),
(11, 'Abricot', 'fruits', 'Description de l\'abricot.'),
(12, 'Pastèque', 'fruits', 'Description de la pastèque.'),
(13, 'Fraise', 'fruits', 'Description de la fraise.'),
(14, 'Cerise', 'fruits', 'Description de la cerise.'),
(15, 'Rhubarbe', 'fruits', 'Description de la rhubarbe.'),
(16, 'Melon', 'fruits', 'Description du melon.'),
(17, 'Cassis', 'fruits', 'Description du cassis.'),
(18, 'Grenade', 'fruits', 'Description de la grenade.'),
(19, 'Ananas', 'fruits', 'Description de l\'ananas.'),
(20, 'Mirabelle', 'fruits', 'Description de la mirabelle.'),
(21, 'Myrtille', 'fruits', 'Description de la myrtille.'),
(22, 'Pamplemousse', 'fruits', 'Description du pamplemousse.'),
(23, 'Prune', 'fruits', 'Description de la prune.'),
(24, 'Mûre', 'fruits', 'Description de la mûre.'),
(25, 'Figue', 'fruits', 'Description de la figue.'),
(26, 'Physalis', 'fruits', 'Description du physalis.'),
(27, 'Pruneau', 'fruits', 'Description du pruneau.'),
(28, 'Kaki', 'fruits', 'Description du kaki.'),
(29, 'Noisette', 'fruits', 'Description de la noisette.'),
(30, 'Framboise', 'fruits', 'Description de la framboise.'),
(31, 'Mangue', 'fruits', 'Description de la mangue.'),
(32, 'Grenadille', 'fruits', 'Description de la grenadille.'),
(33, 'Anone', 'fruits', 'Description de l\'anone.'),
(34, 'Coing', 'fruits', 'Description du coing.'),
(35, 'Orange', 'fruits', 'Description de l\'orange.'),
(36, 'Mandarine', 'fruits', 'Description de la mandarine.'),
(37, 'Chou frisé', 'légumes', 'Description du chou frisé.'),
(38, 'Carotte', 'légumes', 'Description de la carotte.'),
(39, 'Panais', 'légumes', 'Description du panais.'),
(40, 'Poireau', 'légumes', 'Description du poireau.'),
(41, 'Rutabaga', 'légumes', 'Description du rutabaga.'),
(42, 'Endive', 'légumes', 'Description de l\'endive.'),
(43, 'Épinard', 'légumes', 'Description de l\'épinard.'),
(44, 'Navet', 'légumes', 'Description du navet.'),
(45, 'Laitue', 'légumes', 'Description de la laitue.'),
(46, 'Asperge', 'légumes', 'Description de l\'asperge.'),
(47, 'Radis', 'légumes', 'Description du radis.'),
(48, 'Cresson', 'légumes', 'Description du cresson.'),
(49, 'Petit pois', 'légumes', 'Description du petit pois.'),
(50, 'Fève', 'légumes', 'Description de la fève.'),
(51, 'Courgette', 'légumes', 'Description de la courgette.'),
(52, 'Brocoli', 'légumes', 'Description du brocoli.'),
(53, 'Haricot vert', 'légumes', 'Description de l\'haricot vert.'),
(54, 'Concombre', 'légumes', 'Description du concombre.'),
(55, 'Tomate', 'légumes', 'Description de la tomate.'),
(56, 'Aubergine', 'légumes', 'Description de l\'aubergine.'),
(57, 'Poivron', 'légumes', 'Description du poivron.'),
(58, 'Courge', 'légumes', 'Description de la courge.'),
(59, 'Maïs', 'légumes', 'Description du maïs.'),
(60, 'Betterave', 'légumes', 'Description de la betterave.'),
(61, 'Chou romanesco', 'légumes', 'Description du chou romanesco.'),
(62, 'Fenouil', 'légumes', 'Description du fenouil.'),
(63, 'Artichaut', 'légumes', 'Description de l\'artichaut.'),
(64, 'Potiron', 'légumes', 'Description du potiron.'),
(65, 'Chou', 'légumes', 'Description du chou.'),
(66, 'Pomme de terre', 'légumes', 'Description de la pomme de terre.'),
(67, 'Topinambour', 'légumes', 'Description du topinambour.'),
(68, 'Salsifi', 'légumes', 'Description du salsifi.'),
(69, 'Chou-fleur', 'légumes', 'Description du chou-fleur.'),
(70, 'Choux de Bruxelles', 'légumes', 'Description des choux de Bruxelles.'),
(71, 'Céleri-rave', 'légumes', 'Description du céleri-rave.'),
(72, 'Oignon', 'légumes', 'Description de l\'oignon.');


INSERT INTO 
products_of_months (product_of_month_id, month, product_id, featured)
VALUES
(1, 'january', 1, 1),
(2, 'january', 2, 0),
(3, 'january', 3, 0),
(4, 'february', 4, 1),
(5, 'february', 5, 0),
(6, 'february', 6, 0),
(7, 'march', 7, 1),
(8, 'march', 8, 0),
(9, 'march', 9, 0),
(10, 'april', 10, 1),
(11, 'april', 11, 0),
(12, 'april', 12, 0),
(13, 'may', 13, 1),
(14, 'may', 14, 0),
(15, 'may', 15, 0),
(16, 'june', 16, 1),
(17, 'june', 17, 0),
(18, 'june', 18, 0),
(19, 'july', 19, 1),
(20, 'july', 20, 0),
(21, 'july', 21, 0),
(22, 'august', 22, 1),
(23, 'august', 23, 0),
(24, 'august', 24, 0),
(25, 'september', 25, 1),
(26, 'september', 26, 0),
(27, 'september', 27, 0),
(28, 'october', 28, 1),
(29, 'october', 29, 0),
(30, 'october', 30, 0),
(31, 'november', 31, 1),
(32, 'november', 32, 0),
(33, 'november', 33, 0),
(34, 'december', 34, 1),
(35, 'december', 35, 0),
(36, 'december', 36, 0),
(37, 'january', 37, 1),
(38, 'january', 38, 0),
(39, 'january', 39, 0),
(40, 'february', 40, 1),
(41, 'february', 41, 0),
(42, 'february', 42, 0),
(43, 'march', 43, 1),
(44, 'march', 44, 0),
(45, 'march', 45, 0),
(46, 'april', 46, 1),
(47, 'april', 47, 0),
(48, 'april', 48, 0),
(49, 'may', 49, 1),
(50, 'may', 50, 0),
(51, 'may', 51, 0),
(52, 'june', 52, 1),
(53, 'june', 53, 0),
(54, 'june', 54, 0),
(55, 'july', 55, 1),
(56, 'july', 56, 0),
(57, 'july', 57, 0),
(58, 'august', 58, 1),
(59, 'august', 59, 0),
(60, 'august', 60, 0),
(61, 'september', 62, 1),
(62, 'september', 63, 0),
(63, 'september', 64, 0),
(64, 'october', 65, 1),
(65, 'october', 66, 0),
(66, 'october', 67, 0),
(67, 'november', 68, 1),
(68, 'november', 69, 0),
(69, 'november', 70, 0),
(70, 'december', 71, 1),
(71, 'december', 72, 0),
(72, 'december', 73, 0);


INSERT INTO 
users (user_id, profile, email, password, date_of_birth,address, zip_code, city, profile_picture, confirmation_link,confirmation_date_sent, created_date, last_connection)
VALUES
(1, 'administrator', 'admin@example.com', 'test', '2024-01-01', '1 rue du pays imaginaire', '33000', 'Bordeaux', NULL, 1, NULL, NOW(), NULL),
(2, 'user', 'user@example.com', 'test', '2024-01-01', '2 rue du pays imaginaire', '33000', 'Bordeaux', NULL, 1, NULL, NOW(), NULL);
